"""Auditable Response Generation Contracts for SANGYAN.

Epistemic foundation:
- Consumes ONLY structured outputs: AssessmentResult, RetrievalResponse, EvidenceItems, case_facts.
- Generation Service must NEVER modify case facts, evidence, retrieved provisions, or assessment status.
- Every regulatory claim MUST be grounded in a retrieved provision.
- Post-generation validation rejects hallucinated citations and unsupported factual claims.
- Never represents SANGYAN as a court, regulator, or final legal authority.
"""

from datetime import datetime, timezone
from typing import Any
from pydantic import BaseModel, Field

from ai.app.assessment.contracts import AssessmentStatus


class CitationReference(BaseModel):
    """Authoritative citation attached to a generated explanation."""
    provision_id: str
    authority: str | None
    document_identifier: str
    section_clause: str | None = None
    source_url: str | None = None
    citation_text: str
    is_validated: bool = True


class GeneratedFinding(BaseModel):
    """Discrete, citizen-facing finding explanation grounded in evaluated provisions."""
    status: AssessmentStatus
    heading: str
    explanation: str
    cited_provisions: list[str] = Field(default_factory=list)
    cited_evidence: list[str] = Field(default_factory=list)


class GeneratedResponse(BaseModel):
    """Complete, auditable, citizen-facing response generated by SANGYAN."""
    case_id: str
    summary: str
    assessment_status: AssessmentStatus
    findings: list[GeneratedFinding] = Field(default_factory=list)
    supporting_evidence_summary: list[str] = Field(default_factory=list)
    regulatory_basis: list[CitationReference] = Field(default_factory=list)
    missing_information: list[str] = Field(default_factory=list)
    clarification_questions: list[str] = Field(default_factory=list)
    next_steps: list[str] = Field(default_factory=list)
    disclaimers: list[str] = Field(default_factory=list)
    validation_passed: bool = True
    validation_errors: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
